### ISSUE TITLE
如何获取hash中的Id参数，如#member/details/123

### ISSUE THREAD

**Issue by jaryway** [zhaoda/spa#14]
如题，有没有快速获取的方法，还是只能自己写方法？

**Comment by zhaoda** [comment]
定义路由规则的时候route设置成`member/details/:id`，然后在每个视图的回调函数中的第一个参数中可以找到这个id值，比如
```
  var pageShow = {
    route: 'member/details/:id',
    classname: 'show',
    animate: 'slideInLeft',
    title: '',
    view: function(pageData){
      var $page = this,
          id = pageData.requestData[0], // 这里获取的就是第一个匹配的参数id，使用的时候最好进行html实体转换，防止在模板拼装的时候被xss
```

**Comment by jaryway** [comment]
原来是这样。还有个问题，ajax获取内容时，有时可以显示ajax内容有时又没有内容。
```js
define({
    title: 'SPA - 为WebApp设计的路由控制和视图转换框架',
    body: '<nav class="navbar navbar-default navbar-static-top" role="navigation">\
    <div class="navbar-header">\
      <a class="navbar-brand" href="#">通讯录</a>\
    </div>\
    </nav>\
    <div id="member-view-container" class="page-container-navbar">\
        pppsdlpood;;a\
    </div>\
    ',
    init: function (pageData) {
        //console.log(pageData);
        var $view = this;


        // 获取hash
        function getHash(url) {
            url = url || location.href
            return url.replace(/^[^#]*#?\/?(.*)\/?$/, '$1')
        }
        ///console.log(getHash());
        var id = panelData.requestData[0];
        var url_memberview = $("#member_view").attr("data-url");

        seajs.use(["zepto", "template", "member"], function ($) {

            $.ajax({
                url: url_memberview,
                data: { addrid: id },
                cache: false,
                success: function (data, status, xhr) {
                    seajs.use("tpl/memberView", function (template) {
                        console.log($("#member-view-container").length + "\t" + template({ user: data.Data }));
                        $("#member-view-container").html(template({ user: data.Data }));
                    });
                }
            });
        });

        $('.page-container-navbar', $view).trigger('spa:scroll');

    },
    beforeopen: function (panelData) {
        var $view = this;
        console.log(panelData);
        
        //$('.spa-page-bg', $view).css({ opacity: 0 }).transition({ opacity: 0.6 })
    },
})
```
是否有不妥的地方

**Comment by zhaoda** [comment]
确定ajax的success回调执行了么？打印data看看是否正确呢？

**Comment by zhaoda** [comment]
还有视图的框架模板不一定非要写在body里，因为如果卸载body里是不能根据url进行改变的，可以通过`view`回调来设置body，给你一个实例：
```javascript
  var pageShow = {
    route: 'show/:id',
    classname: 'show',
    animate: 'slideInLeft',
    title: '标题',
    view: function(pageData){
      var $page = this,
          context = {},
          body = txTpl( tmpl, context) // body可以是动态的哦！
      
      // 如果有view，那么比如主动执行spa:initpage         
      $doc.trigger('spa:initpage', [$page, {body: body, title: '可以重写标题'}])
    },
    init: function(pageData) {
    },
    afteropen: function(pageData) {
    },
    afterclose: function() {
    }
  }
```

**Comment by jaryway** [comment]
第二个问题产生的原因是，view加载后会生成一个div，这样可以避免第二次访问时再次加载，但是就会产生这样的问题。
···js
define({
    title: 'SPA - 为WebApp设计的路由控制和视图转换框架',
    body: '<nav class="navbar navbar-default navbar-static-top" role="navigation">\
    <div class="navbar-header">\
      <a class="navbar-brand" href="#">通讯录</a>\
    </div>\
    <a href="#" class="btn btn-default navbar-btn btn-link pull-left"><span class="glyphicon glyphicon-chevron-left"></span></a>\
    </nav>\
    <div class="page-container-navbar member-view-container">\
    </div>\
    ',
    init: function (pageData) {
        var $view = this;
        // 获取hash
        function getHash(url) {
            url = url || location.href
            return url.replace(/^[^#]*#?\/?(.*)\/?$/, '$1')
        }
        var id = pageData.requestData[0];
        var url_memberview = $("#member_view").attr("data-url");

        seajs.use(["zepto", "template", "member"], function ($) {
            $.get(url_memberview, { addrid: id }, function (data, status, xhr) {
                seajs.use("tpl/memberView", function (template) {
                    console.log($view);
                    //因为page加载后会生成一个div，避免第二次再加载。此处如果用ID，只会更改第一个div的内容。
                    //$("#uujjuj_999").html(template({ user: data.Data }));
                    //使用last区分，有没有办法让view的id或class唯一
                    $(".member-view-container:last").html(template({ user: data.Data }));
                });
            });
        });

        $('.page-container-navbar', $view).trigger('spa:scroll');

    }
})
```
有没有办法让每一个view的id或class唯一？最常见的场景就是列表-详情。

**Comment by zhaoda** [comment]
同类视图的class应该是相同的，比如列表页、详情页，他们的结构应该是一样的，只是内容不一样。
```javascript
  var pageShow = {
    route: 'show/:id',
    classname: 'show', // 自定义class
    animate: 'slideInLeft',
```

```html
<div class="spa-page spa-page-show" data-id="2" style="z-index: 2002;" data-spa:init="true">
  <div class="spa-page-body" style="opacity: 1; -webkit-transform: translate(0%, 0px);">
```

视图最外的容器有class `spa-page-show`

**Comment by jaryway** [comment]
我看明白了，其实触发initpage，接收的是一个object对象
```js
{body:body,title:title,init:function(){}}
$doc.trigger('spa:initpage', [$page, {object}])
```

**Comment by zhaoda** [comment]
@jaryway 是的！
