### ISSUE TITLE
刚刚在IE下测试了一下，发现支持得不是很好。

### ISSUE THREAD

**Issue by jaryway** [zhaoda/spa#15]
我是使用官网的demo测试。
IE版本：ie11
页面加载后，点击 打开新页面视图 按钮，没有反应，页面打开后点击返回没有返回。ajax事件也没有触发。
是不是不支持IE呀？

**Comment by zhaoda** [comment]
如果要支持ie，请把zepto换成jquery，我们docs demo是用的zepto

**Comment by jaryway** [comment]
原来是这样。这个用在手机端会不会有性能问题，或者有什么坑可以分享一下的。不知什么时候能出详细的文档？还有一个问题，像那种details页面有很多个，我如何在打开的当前view中查找元素？

**Comment by zhaoda** [comment]
最早测试过ie高级版本  后来就没有跟进ie的兼容问题 欢迎参与项目一起解决兼容性问题

**Comment by lin-chao** [comment]
还有一个问题，像那种details页面有很多个，我如何在打开的当前view中查找元素？

---------
```javascript
view: function(pageData) {
    var $page = this
    var $el = $('.youClass', $page)
    console.log($el)
}
```

**Comment by zhaoda** [comment]
@jaryway , @lin-chao 是我们SPA项目主要成员，也欢迎你参与进来，请问你在什么项目上考虑用SPA。

**Comment by jaryway** [comment]
抱歉，过年回家都没时间看。我主要用在开发手机web站点，所以想问问都有什么已知的坑？

**Comment by zhaoda** [comment]
手机端如果只考虑iOS和版本别太低的android，就没太大问题，win和低版本android建议做一套简单的直出页面来适配吧，我们目前在生产环境上的策略也是这样的。
