### ISSUE TITLE
求一份文档~~

### ISSUE THREAD

**Issue by alicecatherine** [zhaoda/spa#20]
而且为什么视图转换的时候，ios微信里顶部会有加载的进度条出现，感觉很不好

**Comment by zhaoda** [comment]
加载进度条是因为发起了ajax或者异步拉取文件引起的，这个应该是微信层面的设计吧？

**Comment by alicecatherine** [comment]
我用过其他的SPA应用框架通过ajax拉取文件，不会造成这种现象。
而且我写了一个demo并没有通过ajax拉取文件，视图转换的时候在微信里仍然有这个现象。（ios）
这个体验很不好

**Comment by alicecatherine** [comment]
看了一下 因为你们对微信端利用iframe做了一个hack导致的，那个hack感觉并没有什么太大的用处 可以去掉吧

**Comment by zhaoda** [comment]
哦？那有可能是因为那个iframe？我们在修改页面title的时候，构建了一个空的iframe，用来hack微信内webview修改失败的情况。

https://github.com/zhaoda/spa/blob/master/src/spa.js#L1911

你把这段代码注释掉试试？

**Comment by zhaoda** [comment]
去掉吧
