### ISSUE TITLE
希望能够得到CDN部署支持

### ISSUE THREAD

**Issue by keliming** [zhaoda/spa#21]
我们已在一个新产品中引入了spa框架，效果挺好的。现在想看看博主能不能将文件放到CDN上，方便我们使用，感激不尽。ps:我们是做企业号应用的，企业号已有支持cdn部署的在这里：http://qydev.weixin.qq.com/cdn/cdnjs.html

**Comment by lin-chao** [comment]
没问题。我加一下

**Comment by zhaoda** [comment]
@lin-chao 很赞啊，我觉得SPA是不是应该做2.0版本了，将过去的经验和问题进行整理，然后文档也跟上的，关键是我们现在没有太多业务来推进这个项目了。

**Comment by keliming** [comment]
@lin-chao @zhaoda 谢谢tx大神们。@lin-chao昨天的演讲很精彩，对我们这些前端菜鸟很有启发，大赞。

**Comment by lin-chao** [comment]
过奖了，@keliming 先用下这个地址吧
http://cdnjs.gtimg.com/cdnjs/libs/spa/1.0.7/spa.min.js

页面上具体的表现我们会整理了统一加。

**Comment by keliming** [comment]
好的，谢谢@lin-chao

**Comment by lin-chao** [comment]
@zhaoda 要推，可以企业号这边一起来，对外我们可以聊一下这个

**Comment by zhaoda** [comment]
现在主要是你们在用，我现在的项目用不上SPA。
