### ISSUE TITLE
多个视图缓存

### ISSUE THREAD

**Issue by alicecatherine** [zhaoda/spa#22]
@@@@

**Comment by alicecatherine** [comment]
URL相同的路由请求，参数不一样 只需创建一个视图缓存

**Comment by zhaoda** [comment]
这违背的了SPA的架构设计，况且如果只保存一个试图，保存哪个呢？
你说的url是包含hash的部分么？还是不包含？

**Comment by alicecatherine** [comment]
是包含#的，但是不包含:param

**Comment by alicecatherine** [comment]
而且我只要我:param不同，默认就创建新的视图缓存 这样在移动端性能分分钟被耗光

**Comment by zhaoda** [comment]
因为:param变动了，等于是切换一个新页面了。

**Comment by alicecatherine** [comment]
有什么解决的方案吗 比如限制当前这个路由下视图缓存的个数

**Comment by zhaoda** [comment]
设置清理页面最多缓存的页面数量行不行？
```js
$doc.trigger('spa:viewcachecount', {count: 5})
```

https://github.com/zhaoda/spa/blob/master/src/spa.js#L1816

**Comment by alicecatherine** [comment]
有问题……5个的时候
https://github.com/zhaoda/spa/blob/master/src/spa.js#L1862
报错Uncaught TypeError: Cannot read property 'html' of undefined

**Comment by zhaoda** [comment]
是在spa:boot事件之前调用的？
你的项目里包含面板视图么？
只是设置5个报错，2、3、4、6……试过么？对了，别设置成1。
```js
$doc.trigger('spa:viewcachecount', {count: 5})
$doc.trigger('spa:boot')
```

**Comment by alicecatherine** [comment]
不包含面板视图
我的意思是视图缓存个数达到count的时候，如果在创建就会报这个错误
不知道为啥 - -！

**Comment by alicecatherine** [comment]
调式了一下 
https://github.com/zhaoda/spa/blob/master/src/spa.js#L1856
你们这块处理的有问题,比如这个value值是page:hashurl:param
然后:param就丢了

**Comment by alicecatherine** [comment]
可惜这个是全局视图缓存，我理想是可以设置当前hash 视图缓存数量为1

**Comment by zhaoda** [comment]
恩，理解你的意思了，但是目前还不是这样的设计，你可以自己改一下底层来实现
