### ISSUE TITLE
loading动画 可以自定义吗?

### ISSUE THREAD

**Issue by xierenyuan** [zhaoda/spa#23]
-.-大大下午好 刚刚看到 说loading 动画 可以自定义 不知道 在哪里自定义 能给一份更详细点的文档吗 谢谢大大呢。

**Comment by zhaoda** [comment]
*   loading的默认html和css
https://github.com/zhaoda/spa/blob/master/src/spa.js#L81
*   我们提供了`spa:loader`事件来重写loading的html和css https://github.com/zhaoda/spa/blob/master/src/spa.js#L1960
```js
// 自定义loading
$doc.trigger('spa:loader', {body: '', style: ''})
```

**Comment by xierenyuan** [comment]
谢谢。
