### ISSUE TITLE
关于面板视图无法使用

### ISSUE THREAD

**Issue by xierenyuan** [zhaoda/spa#26]
你好,我照着你的demo 写了 下面板视图,但是发现触发后 发现 页面并没有出现面板视图 而是一直出现加载中。。。
![image](https://cloud.githubusercontent.com/assets/7599351/8226903/4edc196c-15d5-11e5-902a-d115a1e00bb6.png)
![image](https://cloud.githubusercontent.com/assets/7599351/8226908/57865758-15d5-11e5-97e6-a5df41459e8b.png)
![image](https://cloud.githubusercontent.com/assets/7599351/8226912/5e1c55cc-15d5-11e5-8623-3053956fdf6c.png)

**Comment by zhaoda** [comment]
requirejs之后的回调执行了么？

**Comment by xierenyuan** [comment]
执行呢。
![image](https://cloud.githubusercontent.com/assets/7599351/8227315/e6023c92-15d8-11e5-8dc5-972eadc55623.png)
![image](https://cloud.githubusercontent.com/assets/7599351/8227322/ec214ff0-15d8-11e5-9a62-0a70dc08ef04.png)

**Comment by zhaoda** [comment]
1.是否报错？
2.看看dom里是否已经生成了这个panel，如果生成了，可能是样式问题导致这个menu没有出来，reveal动画需要视图有确定的宽度或者高度设置，你用的revealInRight，就需要将这个menu视图通过样式设定确切的宽度，并且是给menu视图里的第一层子容器设置。

**Comment by xierenyuan** [comment]
找到原因呢 - -。。。因为自己不小心造成的
![image](https://cloud.githubusercontent.com/assets/7599351/8227996/07e3033c-15de-11e5-91f0-600da3f19ee0.png)天哪噜  对了 所有的事件 我看demo 的是
![image](https://cloud.githubusercontent.com/assets/7599351/8228002/1391616a-15de-11e5-9863-bc671be9447e.png)  我在移动使用 可以绑定 tap 什么的不？

**Comment by zhaoda** [comment]
当然可以，我们在移动端都是通过tap事件，但是你要做好防点击穿透等工作

**Comment by zhaoda** [comment]
话说，原因是啥，我咋没看出来？

**Comment by xierenyuan** [comment]
-。-。。。   $doc.trigger("spa:initpanel", [$panel, viewData]);  我写成$panel.trigger("spa:initpanel", [$panel, viewData]);   
 
![image](https://cloud.githubusercontent.com/assets/7599351/8228302/4e42d79c-15e0-11e5-9763-73fa56a0faf9.png) 天哪噜 。。。仿穿透 这是一个悲伤的故事。。。  大神 话说 你为什么不建个 群什么的  我感觉你这个灰常好用

**Comment by zhaoda** [comment]
QQ群？用QQ群是不是显得很low？

**Comment by xierenyuan** [comment]
-。- 不会吧。QQ群对于国人来说 比较普通。貌似这国人用的比较多吧。PS(弱弱的说 要是文档在丰富点 使用的人应该会更多！)

**Comment by zhaoda** [comment]
防止点击穿透的代码参考，如果不考虑pc端，最外侧的判断可以去掉，逻辑很简单，相信你一看就懂。
```js
  // 防止点击穿透
  if(tapEvent == 'tap') {
    $doc.on('touchstart', 'a', function(event) {
      var $target = $(event.currentTarget)
      $target.data('taptime', +new Date())
    })

    $doc.on('click', 'a', function(event) {
      var $target = $(event.currentTarget),
          taptime = $target.data('taptime')

      if(!taptime || (+new Date() - taptime > 500)) {
        event.preventDefault()
        event.stopPropagation()
      }
    })
  }
```

**Comment by xierenyuan** [comment]
好的谢谢。

**Comment by zhaoda** [comment]
你来帮忙贡献代码吧，把你的demo啥的都放上来？写写wiki？

**Comment by xierenyuan** [comment]
好呀。

**Comment by zhaoda** [comment]
期待你的Pull requests

**Comment by zhaoda** [comment]
QQ群的效率太低了，所以还是在github吧，这里基友多。

**Comment by xierenyuan** [comment]
恩恩。  好好
