### ISSUE TITLE
页面切换有异常

### ISSUE THREAD

**Issue by KevinPan** [zhaoda/spa#30]
现在我有四个页面A,B,C,D
我现在按照以下顺序切换页面C-B-A-B-D-C-B-A-B-C
当我切换到最后一个C页面的动画过程中，我看到了D页面

**Comment by zhaoda** [comment]
@KevinPan 你有找到原因么？是SPA的bug，还是某些页面没有设置背景色，透视过去了？

**Comment by KevinPan** [comment]
我觉得可能是SPA的bug，我在使用http://zhaoda.net/spa/docs/也能够出现页面切换过程中闪现其他页面的情况。
请看我的截屏视频：http://pan.baidu.com/s/1sjP3TyX

**Comment by zhaoda** [comment]
@KevinPan 这个视频我没看清楚是怎么操作的，能说明一下操作过程么？

**Comment by KevinPan** [comment]
@zhaoda 现在还没找到一个稳定的重现步骤

**Comment by zhaoda** [comment]
哦，不是毕现？

**Comment by KevinPan** [comment]
@zhaoda 
我这边有一个步骤可以重现：
1. 打开http://zhaoda.net/spa/docs/
2. 点击“打开新页面试图”按钮
3. 点击“确认对话框”按钮
4. 点击“fadeIn”按钮

每次点击按钮的前后请在页面其他地方点击一下货几下

**Comment by zhaoda** [comment]
确实是一个很严重的bug，只要在面板视图关闭的时候，重复的点击面板视图的背景区域，就可以重现这个bug，原因就是这种面板视图有特殊性，就是他的背景区域可以接收点击关闭行为，这个逻辑里没有判断面板是否在关闭中的状态，导致逻辑出现混乱，没有设置好正确的z-index，我已经修复并提交了代码，请review下吧。

**Comment by zhaoda** [comment]
@KevinPan 你看看我的commit https://github.com/zhaoda/spa/commit/15db2778ef20c521ec625c5d7cfbbcfc7d85119a，然后验证最新代码吧。
