### ISSUE TITLE
emulateTransitionEnd扩展函数冲突问题

### ISSUE THREAD

**Issue by lazyhero** [zhaoda/spa#32]
许多主流UI类库都选择使用emulateTransitionEnd为名作为jquery实例的扩展函数；
在与amazeui同时使用时 会造成冲突问题；
建议更改名称；
在我fork过去的spa中我将其改为了emulateTransitionEndBySpa

**Comment by zhaoda** [comment]
下个版本采纳意见，这个问题我还真遇到过

2015-09-06 17:37 GMT+08:00 懒界超人 <notifications@github.com>:
