### ISSUE TITLE
必须要使用requirejs或者seajs模块化方式加载吗？

### ISSUE THREAD

**Issue by guzuomuse** [zhaoda/spa#33]
如果不使用模块化的方法应该如何组织代码？

**Comment by lin-chao** [comment]
可以不用，通过script标签引入就可以

**Comment by guzuomuse** [comment]
恩；也就是原生的办法；这个issue感觉有点2；之所以提出是因为在文档中看到了“可以通过自定义的方式进行模块化组织”；
