### ISSUE TITLE
在手机端访问weishi.com和PC端访问页面表现形式不一样，请问是如何处理的？

### ISSUE THREAD

**Issue by guzuomuse** [zhaoda/spa#34]
是类似于bootstrap添加的sr_only这样样式控制；还是判断终端设备类型，然后调用不同的前台模板来处理的？谢谢。

**Comment by lin-chao** [comment]
后者，服务端通过ua来判断

**Comment by guzuomuse** [comment]
@lin-chao，非常感谢！(ˇˍˇ)

我还以为找到了一种理想中的东西：
不仅仅是responsive，还要如果是mobile或者tablet的终端可以有类似于spa这样的"native" transition效果；
这么看来；可以这么说，还没有一种框架可以实现：mobile app(不是webapp)和 pc web通吃；

我找了好久也没有找到类似的；

之所以有这样的需求是因为：既有网站的业务；也有移动终端的需求；而又只想通过hybrid的方式通过phonegap之类的桥接进行打包；同时打包的生成的app要有"native"的感觉；

看来，目前来讲只能进行分开独立开发了吗？这样要分两套代码来写了，纠结啊！

请问，你有更好的方案吗？谢谢！

**Comment by lin-chao** [comment]
呃。我们的经验并不认为全部采用一套系统好，PC和mobile还有pad上的交互和呈现是各有不同的，并没有一套能搞定全部的而且还能做很好的。

**Comment by guzuomuse** [comment]
got it, thank u :)
