### ISSUE TITLE
你好 我想问下咱们这个spa框架可以整合sui么

### ISSUE THREAD

**Issue by fyunos** [zhaoda/spa#35]
咱们这个spa框架可以整合sui（http://m.sui.taobao.org/components/）么？
如果可以整合的话 请指点下，感激不尽

**Comment by zhaoda** [comment]
首先SUI包含了SPA的功能，视图转换和路由控制，在SPA中使用SUI也没有问题，docs这个用例就是用的bootstrap，SPA和你用哪个UI框架不冲突

2015-12-10 16:28 GMT+08:00 fyunos <notifications@github.com>:
