### ISSUE TITLE
-.-..终于抽时间 写了demo  请zhaoda 大大提意见

### ISSUE THREAD

**Issue by xierenyuan** [zhaoda/spa#38]
-。-。大大晚上好 ,之前 问过你很多问题, 今天终于有空弄了个demo  请大大提提意见 我修改。今天刚刚开始弄的问题还很多,页面 后面继续补上 地址https://github.com/xierenyuan/spa-d

**Comment by zhaoda** [comment]
好棒啊，建议你创建一个gh-pages分支，这样就可以直接看效果了。

2016-03-10 22:56 GMT+08:00 -。-平小平 <notifications@github.com>:

**Comment by zhaoda** [comment]
看了你的代码和目录结构，很有层次，思路清晰，手动点赞。

2016-03-10 23:16 GMT+08:00 赵达 <zd6437@gmail.com>:

**Comment by xierenyuan** [comment]
恩 收到建议. 等我继续完善了 你在帮我看看。大神 早安

**Comment by zhaoda** [comment]
大家互相学习，加油！
