### ISSUE TITLE
spa:initpanel 事件的触发不生效

### ISSUE THREAD

**Issue by hightman** [zhaoda/spa#41]
参见代码行 [spa.js#L1660](https://github.com/zhaoda/spa/blob/master/dist/spa.js#L1660) 此处由于 $panel 尚未被添加到 body 中，我在 chrome/jquery-2.2 中测试时事件未能触发，必须改为 $doc 去触发才行。

**Comment by zhaoda** [comment]
@hightman 
https://github.com/zhaoda/spa/blob/master/dist/spa.js#L1651 这里当时解决替他bug有个注释，你说的问题确实存在，所以先按你说的修复一下。
