### ISSUE TITLE
打开同一个页面（路由），参数不同情况下，不能显示

### ISSUE THREAD

**Issue by nicklao** [zhaoda/spa#43]
例如，打开一个路由为  home/list1，这是能正常要开显示。
然后再打开路由为  home/list2，这时就不能正常显示了，指向是同一路由，后面的list:num 是传参。

**Comment by zhaoda** [comment]
@nicklao 路由规则怎么写的？

**Comment by nicklao** [comment]
route: "docArticleList/category:num"

**Comment by nicklao** [comment]
@zhaoda 路由规则这样写的 route: "home/list:num"

**Comment by zhaoda** [comment]
路由改成 home/list/:num ，链接改成 home/list/1 这样试试呢？你说的不能正常显示，报错了么？还是显示成什么？

**Comment by nicklao** [comment]
@zhaoda  试了，还是不行！情况是没有报错，只是没有显示出任何东西，每打开一次参数不同的路由，就会产生多一个 class="spa-page spa-page-home" 的div，如果有4次传不同的参，就会有4个  class="spa-page spa-page-home" 的div。

**Comment by nicklao** [comment]
指同同一路由，即同一页面，如果有不同的传参，根据参数来作出不同的处理，SPA.JS现在是没有对这种场景处理的方法吗？

**Comment by zhaoda** [comment]
这种情况肯定是支持的，否则路由规则就没有意义了，我怀疑你的代码逻辑有问题，你说打开 home/list1 有内容，那你在回调里拿到 num 的值 1
了么

**Comment by nicklao** [comment]
第一次打开 home/list1 的时候回调能正常拿到num的值1，这时候会spa.js会创建一个class="spa-page spa-page-home" 的div
 第二次打开  home/list2 的时候 什么都没拿到，这 时候spa.js会创建第二个class="spa-page spa-page-home" 的div

**Comment by zhaoda** [comment]
等我在docs里写一个demo，到时候你对比试试

**Comment by nicklao** [comment]
@zhaoda 不用写了！ 我看过demo，又看了一下源码。是有逻辑问题存在！ 此issue可以close。
